services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_pma
    ports:
      - "6080:80"
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./boodark-orange:/var/www/html/themes/boodark-orange
      - ./darkwolf:/var/www/html/themes/darkwolf
      - ./boodark:/var/www/html/themes/boodark
      - ./blueberry:/var/www/html/themes/blueberry
    environment:
      - UPLOAD_LIMIT=64M
      - PMA_ARBITRARY=1
    networks:
      lamp-network:
        ipv4_address: 172.45.0.7



networks:
  lamp-network:
    external: true
